name: Python Linting

on: [push, pull_request]

jobs:
  lint:
    name: Lint Python Code
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]
    runs-on: ${{ matrix.os }}
    steps:
    - uses: actions/checkout@v2
    - name: Setup Miniconda
      uses: conda-incubator/setup-miniconda@v2
      with:
        activate-environment: wavelet_env
        environment-file: environment.yml
        python-version: '3.8.18'
        auto-activate-base: false
    - name: Cache Conda
      uses: actions/cache@v2
      with:
        path: ~/conda_pkgs_dir
        key: ${{ runner.os }}-conda-${{ hashFiles('**/environment.yml') }}
        restore-keys: |
          ${{ runner.os }}-conda-
    - name: Install Dependencies and Lint with pylint
      run: |
        conda activate wavelet_env
        pip install pylint
        pylint $(find . -type f -name "*.py")